spring:
  devtools:
    restart:
      enabled: true   # Enables automatic restarts on code changes
    livereload:
      enabled: true   # Enables LiveReload for automatic browser refresh
  datasource:
    url: jdbc:postgresql://localhost:5433/lamulaapp-db
    username: admin
    password: 123456789
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
    user: admin
    password: 123456789