spring:
  devtools:
    restart:
      enabled: true   # Enables automatic restarts on code changes
    livereload:
      enabled: true   # Enables LiveReload for automatic browser refresh
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lamulaapp-db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:123456789}
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration